Biblioteka/Pages/Authors/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Biblioteka.Models;
using Biblioteka.Repositories.Interfaces;

namespace Biblioteka.Pages.Authors
{
    //[Authorize(Roles = "Admin, Employee")]
    public class CreateModel : PageModel
    {
        private IAuthorRepository _authorRepository;

        public CreateModel(IAuthorRepository authorRepository)
        {
            _authorRepository = authorRepository;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Author Author { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid || Author == null)
            {
                return Page();
            }
            if (Author.image != null)
            {
                if (Author.image.Length > 0 && Author.image.Length < 10000000 && Path.GetExtension(Author.image.FileName) == ".jpg")
                {
                    using (var ms = new MemoryStream())
                    {
                        Author.image.CopyTo(ms);
                        Author.imageData = ms.ToArray();
                    }
                }
                else
                {
                    ModelState.AddModelError("file not pdf or wrong size", "Plik musi być w formacie JPG i nie większy niż 10MB!");
                    TempData["Message"] = $"Error/Plik z zdjęciem musi być w formacie JPG i nie większy niż 10MB!";
                    return RedirectToPage("./Index");
                }        
            }  
            _authorRepository.Add(Author);

            TempData["Message"] = $"Success/Pomyślnie dodano nowego autora.";
            return RedirectToPage("./Index");
        }
    }
}

Biblioteka/Pages/Authors/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Biblioteka.Models;
using Biblioteka.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace Biblioteka.Pages.Authors
{
    [Authorize(Roles = "Admin, Employee, Author")]
    public class EditModel : PageModel
    {
        private IAuthorRepository _authorRepository;

        public EditModel(IAuthorRepository authorRepository)
        {
            _authorRepository = authorRepository;
        }

        [BindProperty]
        public Author Author { get; set; } = default!;

        public IActionResult OnGet(int id)
        {
            var author = _authorRepository.getOne(id);

            if (id == 0)
            {
                author = _authorRepository.GetByMail(User.Identity.Name);
            }


            if (author == null)
            {
                return NotFound();
            }

            Author = author;
            return Page();
        }

        public IActionResult OnPost()
        {
            if (User.IsInRole("Author"))
            {
                Author.email = User.Identity.Name;
                //ModelState.Values
            }

            if (Author.image != null)
                if (Author.image.Length > 0 && Author.image.Length < 10000000 && Path.GetExtension(Author.image.FileName) == ".jpg")
                {
                    using (var ms = new MemoryStream())
                    {
                        Author.image.CopyTo(ms);
                        Author.imageData = ms.ToArray();
                    }
                }
                else
                    ModelState.AddModelError("file not pdf or wrong size", "Plik musi być w formacie JPG i nie większy niż 10MB!");

            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                _authorRepository.Update(Author);
                TempData["UpdateSuccess"] = true;
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AuthorExists(Author.authorId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool AuthorExists(int id)
        {
            var isExisted = _authorRepository.getOne(id);

            return isExisted != null ? true : false;
        }
    }
}

Biblioteka/Pages/BookTypes/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Biblioteka.Repositories.Interfaces;
using Biblioteka.Models;
using Biblioteka.Repositories.DbImplementations;

namespace Biblioteka.Pages.BookTypes
{
    public class CreateModel : PageModel
    {
        private IBookTypeRepository _bookTypeRepository;

        public CreateModel(IBookTypeRepository bookTypeRepository)
        {
            _bookTypeRepository = bookTypeRepository;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public BookType BookType { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public IActionResult OnPost()
        {
          if (!ModelState.IsValid || BookType == null)
            {
                return Page();
            }

            if (_bookTypeRepository.searchBookType(BookType.name) != null)
            {
                ModelState.AddModelError("", "Jest już dodany taki rodzaj książki");
                return Page();
            }
            else
            {
                _bookTypeRepository.Add(BookType);
            }

            return RedirectToPage("./Index");
        }
    }
}

Biblioteka/Pages/BookTypes/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Biblioteka.Models;
using Biblioteka.Repositories.Interfaces;

namespace Biblioteka.Pages.BookTypes
{
    public class EditModel : PageModel
    {
        private IBookTypeRepository _bookTypeRepository;

        public EditModel(IBookTypeRepository bookTypeRepository)
        {
            _bookTypeRepository = bookTypeRepository;
        }

        [BindProperty]
        public BookType BookType { get; set; } = default!;

        public IActionResult OnGet(int id)
        {

            var booktype =  _bookTypeRepository.getOne(id);
            if (booktype == null)
            {
                return NotFound();
            }
            BookType = booktype;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                _bookTypeRepository.Update(BookType);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BookTypeExists(BookType.typeId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool BookTypeExists(int id)
        {
            var isExisted = _bookTypeRepository.getOne(id);

            return isExisted != null ? true : false;
        }
    }
}

Biblioteka/Pages/EmployeeExtraData/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Biblioteka.Models;
using Biblioteka.Repositories.Interfaces;

namespace Biblioteka.Pages.EmployeeExtraData
{
    //[Authorize(Roles = "Admin")]
    public class CreateModel : PageModel
    {
        private IEmployeeDataRepository _employeeDataRepository;
        private IEmployeeRepository _employeeRepository;

        public CreateModel(IEmployeeDataRepository employeeDataRepository, IEmployeeRepository employeeRepository)
        {
            _employeeDataRepository = employeeDataRepository;
            _employeeRepository = employeeRepository;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public EmployeeDataDto EmployeeData { get; set; } = default!;
        
        public IActionResult OnPost(int id)
        {
            if (!ModelState.IsValid || EmployeeData == null)
            {
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        var employeedata = EmployeeData;
                        Console.WriteLine($"Model error: {error.ErrorMessage}");
                    }
                }
                return Page();
            }
            else
            {
                var employeedata = EmployeeData;
                EmployeeData newEmployeeData = new EmployeeData()
                {
                    pesel = EmployeeData.pesel,
                    street = EmployeeData.street,
                    houseNumber = EmployeeData.houseNumber,
                    town = EmployeeData.town,
                    zipCode = EmployeeData.zipCode,
                    phoneNumber = EmployeeData.phoneNumber,
                    birthDate = EmployeeData.birthDate,
                };
                EmployeeData.employeeId = id;
                Employee? employee = _employeeRepository.getOne(id);

                if (EmployeeData != null && employee != null)
                    newEmployeeData.employee = employee;

                _employeeDataRepository.Add(newEmployeeData);

                return RedirectToPage("../Employees/Index");
            }
        }
    }
}

Biblioteka/Pages/EmployeeExtraData/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Biblioteka.Models;
using Biblioteka.Repositories.Interfaces;

namespace Biblioteka.Pages.EmployeeExtraData
{
    //[Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {
        private IEmployeeDataRepository _employeeDataRepository;
        private IEmployeeRepository _employeeRepository;

        public EditModel(IEmployeeDataRepository employeeDataRepository,  IEmployeeRepository employeeRepository)
        {
            _employeeDataRepository = employeeDataRepository;
            _employeeRepository = employeeRepository;
        }


        [BindProperty]
        public EmployeeDataDto EmployeeData { get; set; } = new EmployeeDataDto();

        public IActionResult OnGet(int id)
        {
            var employeedata =  _employeeDataRepository.getOne(id);
            if (employeedata == null)
            {
                return NotFound();
            }

            EmployeeData = new EmployeeDataDto
            {
                employeeId = employeedata.employeeId,
                pesel = employeedata.pesel,
                street = employeedata.street,
                houseNumber = employeedata.houseNumber,
                town = employeedata.town,
                zipCode = employeedata.zipCode,
                phoneNumber = employeedata.phoneNumber,
                birthDate = employeedata.birthDate,
            };
            
            return Page();
        }

        public IActionResult OnPost(int id)
        {
            if (!ModelState.IsValid || EmployeeData == null)
            {
                return Page();
            }
            else
            {
                var existingEmployeeData = _employeeDataRepository.getOne(EmployeeData.employeeId);
                if (existingEmployeeData == null)
                {
                    return NotFound();
                }

                existingEmployeeData.pesel = EmployeeData.pesel;
                existingEmployeeData.street = EmployeeData.street;
                existingEmployeeData.houseNumber = EmployeeData.houseNumber;
                existingEmployeeData.town = EmployeeData.town;
                existingEmployeeData.zipCode = EmployeeData.zipCode;
                existingEmployeeData.phoneNumber = EmployeeData.phoneNumber;
                existingEmployeeData.birthDate = EmployeeData.birthDate;

                EmployeeData.employeeId = id;
                Employee? employee = _employeeRepository.getOne(id);

                if (employee != null)
                    existingEmployeeData.employee = employee;
                _employeeDataRepository.Update(existingEmployeeData);
                return RedirectToPage("../Employees/Index");

            }
        }

        private bool EmployeeDataExists(int id)
        {
            var isExisted = _employeeDataRepository.getOne(id);

            return isExisted != null ? true : false;
        }
    }
}

Biblioteka/Pages/Employees/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Biblioteka.Models;
using Biblioteka.Repositories.Interfaces;

namespace Biblioteka.Pages.Employees
{
    //[Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {
        private IEmployeeRepository _employeeRepository;
        private Biblioteka.Context.BibContext _bibContext;

        public EditModel(IEmployeeRepository employeeRepository, Biblioteka.Context.BibContext bibContext)
        {
            _employeeRepository = employeeRepository;
            _bibContext = bibContext;
        }

        [BindProperty]
        public Employee Employee { get; set; } = default!;
        public List<SelectListItem>? Positions { get; set; }

        [BindProperty]
        public string PositionId { get; set; } = default!;

        public IActionResult OnGet(int id)
        {
            Positions = _bibContext.Position.Select(p => new SelectListItem { Value = p.positionId.ToString(), Text = p.name }).ToList();

            var employee = _employeeRepository.getOne(id);
            if (employee == null)
            {
                return NotFound();
            }
            Employee = employee;
            return Page();
        }

        public IActionResult OnPost()
        {
            Position? foundPosition = _bibContext.Position.FirstOrDefault(p => p.positionId.ToString().Equals(PositionId.ToString()));

            if(foundPosition != null && Employee != null)
                Employee.position = foundPosition;
            else
                ModelState.AddModelError("", "Stanowisko jest wymagane.");

            //ModelState.Remove("Employee.position");
           // ModelState.Remove("Employee.employeeData");

            if (!ModelState.IsValid || Employee == null)
            {
                Positions = _bibContext.Position.Select(p => new SelectListItem { Value = p.positionId.ToString(), Text = p.name }).ToList();

                return Page();
            }

            try
            {
                _employeeRepository.Update(Employee);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EmployeeExists(Employee.employeeId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            
            return RedirectToPage("./Index");
        }

        private bool EmployeeExists(int id)
        {
            var isExisted = _employeeRepository.getOne(id);

            return isExisted != null ? true : false;
        }
    }
}

Biblioteka/Pages/Genres/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Biblioteka.Repositories.Interfaces;
using Biblioteka.Models;
using Microsoft.AspNetCore.Mvc;
using Biblioteka.Repositories;
using Microsoft.EntityFrameworkCore;

namespace Biblioteka.Pages.Genres
{
    public class IndexModel : PageModel
    {
        private IGenreRepository _genreRepository;

        public IndexModel(IGenreRepository genreRepository)
        {
            _genreRepository = genreRepository;
        }

        public IList<Genre> Genre { get;set; } = default!;

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }

        public void OnGet()
        {
            if (!string.IsNullOrEmpty(SearchTerm))
            {
                Genre = new List<Genre> { _genreRepository.searchGenre(SearchTerm) };
            }
            else
            {
                // Jeśli nazwa nie jest określona, pobierz wszystkie wydawnictwa
                Genre = _genreRepository.getAll();
            }
        }
        public IActionResult OnPostDeleteGenre(int genreId)
        {
            var genre = _genreRepository.getOne(genreId);
            if(genre == null)
            {
                TempData["Message"] = $"Error/Brak gatunku o id: {genreId}.";
                return RedirectToPage("./Index");
            }
            _genreRepository.Delete(genreId);
            TempData["Message"] = $"Success/Pomyślnie usunięto gatunek: \"{genre.name}\" ";
            return RedirectToPage("./Index");
        }
    }
}

Biblioteka/Pages/Genres/Create.cshtml
@page
@model Biblioteka.Pages.Genres.CreateModel

@{
    ViewData["Title"] = "Create";
}
<link rel="stylesheet" href="~/css/Shared/action_buttons.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Genres/create.css" asp-append-version="true" />

<div class="main_container padding_top_1rem">
    <div class="list_header">
        <h3>Dodawanie nowego gatunku</h3>
    </div>
    <div class="genre_add_form_div">
        <form id="genre_form" method="post">
            <div class="d-flex flex-row justify-content-center align-items-center gap-5 w-75 genre_add_in_form_div">
                <div class="form-floating w-75">
                    <input asp-for="Genre.name" class="form-control" />
                    <label asp-for="Genre.name" class="control-label"></label>
                    <span asp-validation-for="Genre.name" class="text-danger"></span>
                </div>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger mt-2"></div>
            <button class="action-button biggest-button action-default mt-4" id="addSubmit" type="submit">Dodaj gatunek</button>
            <a asp-page="./Index">
                <div class="action-button action-cancel mt-3 back-btn">Wróć</div>
            </a> 
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Biblioteka/Pages/Genres/Edit.cshtml
@page
@model Biblioteka.Pages.Genres.EditModel

@{
    ViewData["Title"] = "Edit";
}

<link rel="stylesheet" href="~/css/Shared/action_buttons.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Genres/create.css" asp-append-version="true" />

<div class="main_container padding_top_1rem">
    <div class="list_header">
        <h3>Edycja gatunku: "@Model.Genre.name"</h3>
    </div>
    <div class="genre_add_form_div">
        <form id="genre_form" method="post">
            <input type="hidden" asp-for="Genre.genreId" />
            <div class="d-flex flex-row justify-content-center align-items-center gap-5 w-75 genre_add_in_form_div">
                <div class="form-floating w-75">
                    <input asp-for="Genre.name" class="form-control" />
                    <label asp-for="Genre.name" class="control-label"></label>
                    <span asp-validation-for="Genre.name" class="text-danger"></span>
                </div>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger mt-2"></div>
            <button class="action-button biggest-button action-default mt-4" id="addSubmit" type="submit">Zapisz zmiany</button>
            <a asp-page="./Index">
                <div class="action-button action-cancel mt-3 back-btn">Wróć</div>
            </a>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Biblioteka/Pages/Genres/Index.cshtml
@page
@model Biblioteka.Pages.Genres.IndexModel

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="~/css/Shared/action_buttons.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Shared/table_style.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Shared/notification_style.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Genres/index.css" asp-append-version="true" />

<div>
    <partial name="_UnderHeaderGenre" />

    <div class="search_div">
        <form method="get" asp-page="./Index">
            <input type="text" placeholder="Wyszukaj gatunek" name="SearchTerm" value="@Model.SearchTerm">
            <button type="submit">
                <i class="fas fa-search"></i>
            </button>
        </form>
    </div>

    <dialog id="delete_genre_dialog">
        <i class="fa-solid fa-circle-xmark dialog-exit"></i>
        <form method="post" asp-page-handler="DeleteGenre">
            <input type="hidden" name="genreId" value="1">
            <p class="dialog_header">Usuwanie gatunku</p>
            <p class="dialog_content">Czy napewno chcesz usunąć ten gatunek ?</p>
            <div class="d-flex flex-row justify-content-center align-items-center">
                <button type="button" class="action-button action-cancel"><i class="fa-solid fa-xmark"></i>Nie, anuluj</button>
                <button type="submit" class="action-button action-delete"><i class="fa-solid fa-trash-can"></i>Tak, usuń</button>
            </div>
        </form>
    </dialog>

    <div class="move_right">
        <button class="action-button big-button action-default">
            <a class="nav-link text-light" asp-page="Create">Dodaj nowy gatunek</a>
        </button>
    </div>

    <div class="table_div table-responsive w-75">
        <table class="table table-striped text-center">
            <thead class="table-header-style">
                <tr>
                    <th class="align-middle">
                        @Html.DisplayNameFor(model => model.Genre[0].name)
                    </th>
                    <th class="align-middle">Akcja</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Genre)
                {
                    <tr>
                        <td class="align-middle genre_name">
                            @Html.DisplayFor(modelItem => item.name)
                        </td>
                        <td class="align-middle action_div">
                            <a class="lightText" asp-page="./Edit" asp-route-id="@item.genreId">
                                <div class="action-button action-confirm mr-2"><i class="fa-solid fa-pen"></i>Edytuj</div>
                            </a>
                            <button class="action-button action-delete"><i class="fa-solid fa-trash-can"></i><p class="hidden-genreId d-none">@item.genreId</p>Usuń</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @if (!Model.Genre.Any())
        {
            // handle empty list
        }
    </div>
    @{
        if (TempData["Message"] != null)
        {
            <div class="notification_div">
                @if (TempData["Message"]?.ToString()?.Split("/")[0] == "Success")
                {
                    <div>
                        <i class="fa-solid fa-check success_notification_icon"></i>
                    </div>
                }
                else
                {
                    <div>
                        <i class="fa-solid fa-circle-exclamation error_notification_icon"></i>
                    </div>
                }
                <div class="notification-content">
                    @if (TempData["Message"]?.ToString()?.Split("/")[0] == "Success")
                    {
                        <p class="notification-header-success">Sukces!</p>
                    }
                    else
                    {
                        <p class="notification-header-error">Błąd!</p>
                    }
                    <p class="notification-message">@TempData["Message"]?.ToString()?.Split("/")[1]</p>
                </div>
                <div class="hide-notification">
                    <i class="fa-solid fa-xmark"></i>
                </div>
            </div>
        }
    }
</div>
<script src="~/js/Genre/ModalDialogRunner.js"></script>
<script src="~/js/Borrowing/Notification.js"></script>