Biblioteka/Pages/Authors/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Biblioteka.Models;
using Biblioteka.Repositories.Interfaces;

namespace Biblioteka.Pages.Authors
{
    //[Authorize(Roles = "Admin, Employee")]
    public class DetailsModel : PageModel
    {
        private IAuthorRepository _authorRepository;

        public DetailsModel(IAuthorRepository authorRepository)
        {
            _authorRepository = authorRepository;
        }

        public Author Author { get; set; } = default!; 

        public IActionResult OnGet(int id)
        {

            var author = _authorRepository.getOne(id);

            if (author == null)
                return NotFound();
            else 
                Author = author;

            return Page();
        }
    }
}

Biblioteka/Pages/Authors/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Biblioteka.Models;
using Biblioteka.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace Biblioteka.Pages.Authors
{
    [Authorize(Roles = "Admin, Employee, Author")]
    public class EditModel : PageModel
    {
        private IAuthorRepository _authorRepository;

        public EditModel(IAuthorRepository authorRepository)
        {
            _authorRepository = authorRepository;
        }

        [BindProperty]
        public Author Author { get; set; } = default!;

        public IActionResult OnGet(int id)
        {
            var author = _authorRepository.getOne(id);

            if (id == 0)
            {
                author = _authorRepository.GetByMail(User.Identity.Name);
            }


            if (author == null)
            {
                return NotFound();
            }

            Author = author;
            return Page();
        }

        public IActionResult OnPost()
        {
            if (User.IsInRole("Author"))
            {
                Author.email = User.Identity.Name;
                //ModelState.Values
            }

            if (Author.image != null)
                if (Author.image.Length > 0 && Author.image.Length < 10000000 && Path.GetExtension(Author.image.FileName) == ".jpg")
                {
                    using (var ms = new MemoryStream())
                    {
                        Author.image.CopyTo(ms);
                        Author.imageData = ms.ToArray();
                    }
                }
                else
                    ModelState.AddModelError("file not pdf or wrong size", "Plik musi być w formacie JPG i nie większy niż 10MB!");

            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                _authorRepository.Update(Author);
                TempData["UpdateSuccess"] = true;
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AuthorExists(Author.authorId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool AuthorExists(int id)
        {
            var isExisted = _authorRepository.getOne(id);

            return isExisted != null ? true : false;
        }
    }
}

Biblioteka/Pages/BookTypes/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Biblioteka.Models;
using Biblioteka.Repositories.Interfaces;

namespace Biblioteka.Pages.BookTypes
{
    public class EditModel : PageModel
    {
        private IBookTypeRepository _bookTypeRepository;

        public EditModel(IBookTypeRepository bookTypeRepository)
        {
            _bookTypeRepository = bookTypeRepository;
        }

        [BindProperty]
        public BookType BookType { get; set; } = default!;

        public IActionResult OnGet(int id)
        {

            var booktype =  _bookTypeRepository.getOne(id);
            if (booktype == null)
            {
                return NotFound();
            }
            BookType = booktype;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                _bookTypeRepository.Update(BookType);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BookTypeExists(BookType.typeId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool BookTypeExists(int id)
        {
            var isExisted = _bookTypeRepository.getOne(id);

            return isExisted != null ? true : false;
        }
    }
}

Biblioteka/Pages/Books/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Biblioteka.Repositories.Interfaces;
using Biblioteka.Models;
using Microsoft.AspNetCore.Identity;
using Biblioteka.Areas.Identity.Data;
using Microsoft.EntityFrameworkCore;
using Serilog;
using PdfSharp.Pdf.IO;
using System.IO;
using PdfSharp.Pdf;
using Biblioteka.Repositories;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using iText.Commons.Actions.Contexts;

namespace Biblioteka.Views.Books
{
    public class DetailsModel : PageModel
    {
        private UserManager<BibUser> _userManager;
        private IBookRepository _bookRepository;
        private IBookOpinionRepository _bookOpinionRepository;
        private IReaderRepository _readerRepository;
        private IAuthorRepository _authorRepository;
        private IEmployeeRepository _employeeRepository;
        private IBorrowingRepository _borrowingRepository;


        public DetailsModel(
            UserManager<BibUser> userManager,
            IBookRepository bookRepository,
            IBookOpinionRepository bookOpinionRepository, IReaderRepository readerRepository, IAuthorRepository authorRepository, IEmployeeRepository employeeRepository, IBorrowingRepository borrowingRepository)
        {
            _userManager = userManager;
            _bookRepository = bookRepository;
            _bookOpinionRepository = bookOpinionRepository;
            _readerRepository = readerRepository;
            _authorRepository = authorRepository;
            _employeeRepository = employeeRepository;
            _borrowingRepository = borrowingRepository; 

        }
        [BindProperty]
        public List<Book_Opinions> Opinions { get; set; } = default!;

        [BindProperty]
        public Book_OpinionsDto User_Opinion { get; set; } = default!;

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel : IValidatableObject
        {
            [Required(ErrorMessage = "Przewidywana data zwrotu książki jest obowiązkowa."),
                Display(Name = "Przewidywana data zwrotu")]
            public DateTime predictedEndDate { get; set; }
            public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
            {
                if (predictedEndDate <= DateTime.Today)
                {
                    yield return new ValidationResult("Przewidywana data zwrotu nie może być z przeszłości!", new[] { "predictedEndDate" });
                }
            }
        }

        //[BindProperty]
        public BookDto Book { get; set; }
        public Book bookModel { get; set; }
        public bool IsRatingAdded { get; set; }
        public BibUser user;

        public List<Author> Authors { get; set; }

        public IActionResult OnGet(int id)
        {
            var book = _bookRepository.getOne(id);
            bookModel = book;
            Opinions = _bookOpinionRepository.getOpinionsForBook(book);

            Reader reader;

            if (User.IsInRole("Reader") && !User.IsInRole("Employee"))
            {
                reader = _readerRepository.GetByMail(User.Identity.Name);

                IsRatingAdded = Opinions.ToList().Where(o => (o.readerId == reader.readerId) && (o.bookId == book.bookId)).Any();
            }
            else
            {
                IsRatingAdded = true;
            }

            if (book == null)
            {
                return NotFound();
            }
            else
            {
                Book = new BookDto
                {
                    bookId = book.bookId,
                    title = book.title,
                    ISBN = book.ISBN,
                    description = book.description,
                    availableCopys = book.availableCopys,
                    ratingAVG = book.ratingAVG,
                    releaseDate = book.releaseDate,
                    floor = book.floor,
                    alley = book.alley,
                    rowNumber = book.rowNumber
                };

                var authors = _authorRepository.getAll().Where(a => a.books.Any(b => b.bookId == id)).ToList();

                if(authors != null)
                {
                    Authors = authors;
                }
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAddBorrowing(int bookId)
        {
            var context = new ValidationContext(this)
            {
                MemberName = nameof(this.Input)
            };
            bool isPredictedEndDateValid = Validator.TryValidateProperty(this.Input, context, new List<ValidationResult>());
            
            if (!isPredictedEndDateValid)
            {
                TempData["Message"] = $"Error/Formularz został wypełniony błędnie.";
                return  RedirectToPage("./Details", new { id = bookId });
            }
            var user = await _userManager.GetUserAsync(User);
            Reader? reader = _readerRepository.GetByMail(user.Email);

            if (reader == null)
            {
                TempData["Message"] = $"Error/Nie można odnaleźć użytkownika w bazie.";
                return RedirectToPage("./Details", new { id = bookId });
            }

            List<Employee> employeeList = _employeeRepository.GetAll();

            if (!employeeList.Any())
            {
                TempData["Message"] = $"Error/Brak pracownika mogącego obsłużyć wypożyczenie.";
                return RedirectToPage("./Details", new { id = bookId });
            }

            Random random = new Random();
            int a = random.Next(0, employeeList.Count);
            Employee randomEmployee = employeeList[a];           
            Book? book = _bookRepository.getOne(bookId);

            if (book == null)
            {
                TempData["Message"] = $"Error/Brak książki o podanym id.";
                return RedirectToPage("./Details", new { id = bookId });
            }

            var borrowing = new Borrowing();
            borrowing.book = book;
            borrowing.employee = randomEmployee;
            borrowing.borrowDate = DateTime.Now;
            borrowing.plannedReturnDate = Input.predictedEndDate;
            borrowing.returnDate = null;
            borrowing.bookLost = false;
            borrowing.Confirmation = false;
            borrowing.IsPaid = false;
            borrowing.IsReturned = false;   
            borrowing.LateFee = 0;

            borrowing.readers.Add(new Reader_Borrowings
            {
                reader = reader,
                borrow = borrowing,
            });

            _borrowingRepository.Add(borrowing);

            book.availableCopys -= 1;
            _bookRepository.Update(book);

            TempData["Message"] = $"Success/Pomyślnie dokonano wypożyczenia książki: \"{book.title}\" " +
                                $"w dniach {DateTime.Now.ToString("dd.MM.yyyy")} - {Input.predictedEndDate.ToString("dd.MM.yyyy")}.";

            return RedirectToPage("../Borrowings/IndexReader");
        }

        public IActionResult OnPostAddOpinion(int bookId)
        {
            var id = bookId; //Book.bookId;

            if (!ModelState.IsValid)
            {
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.WriteLine($"Model error: {error.ErrorMessage}");
                    }

                }
                return OnGet(id);
            }

            //ModelState.Remove("Book.ISBN");
            // ModelState.Remove("Book.genre");
            //ModelState.Remove("Book.publisher");
            //ModelState.Remove("Book.type");
            //ModelState.Remove("Book.title");
            //ModelState.Remove("Book.description");
            //ModelState.Remove("User_Opinion.reader");
            // ModelState.Remove("User_Opinion.book");

            var existingBook = _bookRepository.getOne(id);

            //existingBook.title = Book.title;
            //existingBook.ISBN = Book.ISBN;
            //existingBook.description = Book.description;
            //existingBook.availableCopys = Book.availableCopys;
            //existingBook.ratingAVG = Book.ratingAVG;
            //existingBook.releaseDate = Book.releaseDate;
            //existingBook.floor = Book.floor;
            //existingBook.alley = Book.alley;
            //existingBook.rowNumber = Book.rowNumber;



            var user_opinion = User_Opinion;
            Book_Opinions newUser_Opinion = new Book_Opinions()
            {
                bookId = existingBook.bookId,
                readerId = User_Opinion.readerId,
                rating = User_Opinion.rating,
                addedDate = DateTime.Now,
                opinion = User_Opinion.opinion,
            };

            if (User.IsInRole("Reader") && !User.IsInRole("Employee"))
            {
                newUser_Opinion.reader = _readerRepository.GetByMail(User.Identity.Name);
            }


            newUser_Opinion.book = existingBook;

            var opinionsCount = _bookOpinionRepository.getOpinionsForBook(existingBook).Count;

            if (existingBook.ratingAVG == null)
            {
                existingBook.ratingAVG = Math.Round(User_Opinion.rating, 2);
            }
            else
            {
                double? newRating = ((existingBook.ratingAVG * opinionsCount) + User_Opinion.rating) / (opinionsCount + 1);
                existingBook.ratingAVG = Math.Round((double)newRating, 2);
            }

            User_Opinion.addedDate = DateTime.Now;


            var opinion = newUser_Opinion;
            var booknew = existingBook;

            _bookRepository.Update(booknew);
            _bookOpinionRepository.Add(opinion);


            return RedirectToPage("./Details", new { id = existingBook.bookId });

Biblioteka/Pages/Employees/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Biblioteka.Models;
using Biblioteka.Repositories.Interfaces;
using Biblioteka.Context;
using Microsoft.AspNetCore.Mvc;
using Biblioteka.Repositories.DbImplementations;
using Biblioteka.Repositories;

namespace Biblioteka.Pages.Employees
{
    //[Authorize(Roles = "Admin")]
    public class IndexModel : PageModel
    {
        private IEmployeeRepository _employeeRepository;
        private IUserRepository _userRepository;

        public IndexModel(IEmployeeRepository employeeRepository, IUserRepository userRepository)
        {
            _employeeRepository = employeeRepository;
            _userRepository = userRepository;
        }

        public IList<Employee> Employee { get; set; } = default!;
        public string SearchTerm { get; set; }

        public void OnGet(string searchTerm)
        {
            SearchTerm = searchTerm;
            Employee = _employeeRepository.SearchEmployees(SearchTerm);
        }

        public IActionResult OnPostDeleteEmployee(int employeeId)
        {
            var employee = _employeeRepository.getOne(employeeId);

            if (employee != null)
            {
                var user = _userRepository.GetOne(employee.name, employee.surname, employee.email);

                try
                {
                    _userRepository.Delete(user);
                    _employeeRepository.Delete(employeeId);
                    TempData["Message"] = $"Success/Pomyślnie usunięto pracownika {employee.name} {employee.surname}" +
                    $" zatrudnionego dnia {employee.dateOfEmployment.ToString("dd.MM.yyyy")}.";
                }
                catch (Exception)
                {
                    TempData["Message"] = $"Error/Konto wybranego pracownika nie istnieje.";
                }                
            }
            else
            {
                TempData["Message"] = $"Error/Brak pracownika o takim ID.";
            }
            return RedirectToPage("./Index", new { searchTerm = "" });
        }
    }
}

Biblioteka/Pages/Employees/Details.cshtml
@page
@model Biblioteka.Pages.Employees.DetailsModel

@{
    ViewData["Title"] = "Details";
}
<partial name="_UnderHeaderEmployeeDetails" />

<link rel="stylesheet" href="~/css/Shared/action_buttons.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Employees/details.css" asp-append-version="true" />

<div class="main_container">
    <div class="main-header">
        <div class="image-container">
            <img id="user-photo" src="~/images/user_photo.jpg" />
            <i class="fa-solid fa-pen-to-square"></i>
        </div>
        <h1>@Model.Employee.name @Model.Employee.surname</h1>
        <div class="header-buttons">
            <button class="action-button action-details">
                <a class="lightText" asp-page="./Edit" asp-route-id="@Model.Employee?.employeeId">Edytuj dane ogólne</a>
            </button>
            @if (Model.EmployeeData == null)
            {
                <button class="action-button action-confirm">
                    <a class="lightText" asp-page="../EmployeeExtraData/Create" asp-route-id="@Model.Employee?.employeeId">Dodaj dane szczegółowe</a>
                </button>
            }
            else
            {
                <button class="action-button action-details">
                    <a class="lightText" asp-page="../EmployeeExtraData/Edit" asp-route-id="@Model.EmployeeData?.employeeId">Edytuj dane szczegółowe</a>
                </button>
            }
            <button class="action-button action-default">
                <a class="lightText" asp-page="./Index">Wróć do listy pracowników</a>
            </button>
        </div>
    </div>
    <div class="general-info">
        <h3>Dane ogólne</h3>
        <h4>Stanowisko</h4>
        @{
            if (Model.Employee.position == null)
            {
                <p>Nie podano</p>
            }
            else
            {
                <p>@Model.Employee.position</p>
            }
        }
        <h4>Data Zatrudnienia</h4>
        <p> @String.Format("{0:yyyy-MM-dd}", Model.Employee.dateOfEmployment)</p>
        <h4>Numer Telefonu</h4>
        <p>@Model.EmployeeData.phoneNumber</p>
    </div>
    <div>
        <h3 id="toggle-details" style="cursor:pointer;">
            Dane szczegółowe
            <span id="toggle-text" style="font-size: smaller; color: #e6e6e6;">(rozwiń)</span>
        </h3>
        <div id="specific-info" class="hidden">
            <partial name="~/Pages/EmployeeExtraData/_DetailsPartial.cshtml" model="Model" />
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var toggleHeader = document.getElementById("toggle-details");
        var specificInfo = document.getElementById("specific-info");
        var toggleText = document.getElementById("toggle-text");

        toggleHeader.addEventListener("click", function () {
            if (specificInfo.classList.contains("hidden")) {
                specificInfo.classList.remove("hidden");
                specificInfo.classList.add("visible");
                toggleText.textContent = "(schowaj)";
            } else {
                specificInfo.classList.remove("visible");
                specificInfo.classList.add("hidden");
                toggleText.textContent = "(rozwiń)";
            }
        });
    });
</script>

Biblioteka/Pages/Employees/Edit.cshtml
@page
@model Biblioteka.Pages.Employees.EditModel

@{
    ViewData["Title"] = "Edit";
}
<partial name="_UnderHeaderEdit" />

<link rel="stylesheet" href="~/css/Shared/action_buttons.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Employees/Edit.css" asp-append-version="true" />
<div class="main_container">

            <div class="edit-form">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Employee.employeeId" />
                    <div class="form-group">
                        <label asp-for="Employee.name" class="control-label"></label>
                        <input asp-for="Employee.name" class="form-control" />
                        <span asp-validation-for="Employee.name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Employee.surname" class="control-label"></label>
                        <input asp-for="Employee.surname" class="form-control" />
                        <span asp-validation-for="Employee.surname" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Employee.dateOfEmployment" class="control-label"></label>
                        <input asp-for="Employee.dateOfEmployment" class="form-control" />
                        <span asp-validation-for="Employee.dateOfEmployment" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Employee.position" class="control-label"></label>
                        <select asp-for="@Model.PositionId" class="form-control" asp-items="Model.Positions"></select>
                    </div>
                    <div class="form_buttons">
                        <div class="form-group">
                            <input type="submit" value="Zapisz" class="action-button action-confirm" />
                        </div>
                        <div>
                            <a class="lightText action-button action-default" asp-page="./Index">Wróć</a>
                        </div>
                    </div>
                   
                </form>
            </div>

</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Biblioteka/Pages/Employees/Index.cshtml
@page
@model Biblioteka.Pages.Employees.IndexModel

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="~/css/Shared/action_buttons.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Shared/table_style.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Shared/notification_style.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Employees/index.css" asp-append-version="true" />

<div>
    <partial name="_UnderHeaderEmployees" />

    <div class="search_div">
        <form method="get" asp-page="./Index">
            <input type="text" placeholder="Wyszukaj pracownika" name="SearchTerm" value="@Model.SearchTerm">
            <button type="submit">
                <i class="fas fa-search"></i>
            </button>
        </form>
    </div>

    <div class="move_right">
        <button class="action-button big-button action-default">
            <a class="nav-link lightText" asp-area="Identity" asp-page="/Account/EmployeeRegister">Dodaj nowego pracownika</a>
        </button>
    </div>

    <div class="table_div table-responsive">
        <dialog id="delete_employee_dialog">
            <i class="fa-solid fa-circle-xmark dialog-exit"></i>
            <form method="post" asp-page-handler="DeleteEmployee">
                <input type="hidden" name="employeeId" value="1">
                <p class="dialog_header">Usuwanie pracownika</p>
                <p class="dialog_content">Czy napewno chcesz usunąć tego pracownika ?</p>
                <div class="d-flex flex-row justify-content-center align-items-center">
                    <button type="button" class="action-button action-cancel"><i class="fa-solid fa-xmark"></i>Anuluj</button>
                    <button type="submit" class="action-button action-delete"><i class="fa-solid fa-trash-can"></i>Usuń</button>
                </div>
            </form>
        </dialog>

        <table class="table table-striped text-center">
            <thead class="table-header-style">
                <tr>
                    <th class="align-middle">
                        @Html.DisplayNameFor(model => model.Employee[0].name)
                    </th>
                    <th class="align-middle">
                        @Html.DisplayNameFor(model => model.Employee[0].surname)
                    </th>
                    <th class="align-middle">
                        @Html.DisplayNameFor(model => model.Employee[0].dateOfEmployment)
                    </th>
                    <th class="align-middle">Akcja</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Employee)
                {
                    <tr>
                        <td class="align-middle td_employee_name">
                            @Html.DisplayFor(modelItem => item.name)
                        </td>
                        <td class="align-middle td_employee_surname">
                            @Html.DisplayFor(modelItem => item.surname)
                        </td>
                        <td class="align-middle td_employment_date">
                            @item.dateOfEmployment.ToString("dd.MM.yyyy")
                        </td>
                        <td class="align-middle action_div">
                            @if (item.employeeData == null)
                            {
                                <button class="action-button action-confirm mr-2"><i class="fa-solid fa-plus"></i><a class="lightText" asp-page="../EmployeeExtraData/Create" asp-route-id="@item.employeeId">Dodaj dane szczegółowe</a></button>
                            }
                            <button class="action-button action-details mr-2"><i class="fa-solid fa-circle-info"></i><a class="lightText" asp-page="./Details" asp-route-id="@item.employeeId">Szczegóły</a></button>
                            <button class="action-button action-delete"><i class="fa-solid fa-trash-can"></i>Usuń<p class="hidden-employeeId d-none">@item.employeeId</p></button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @if (!Model.Employee.Any())
        {
            // handle empty list 
        }
    </div>
    @{
        if (TempData["Message"] != null)
        {
            <div class="notification_div">
                @if (TempData["Message"]?.ToString()?.Split("/")[0] == "Success")
                {
                    <div>
                        <i class="fa-solid fa-check success_notification_icon"></i>
                    </div>
                }
                else
                {
                    <div>
                        <i class="fa-solid fa-circle-exclamation error_notification_icon"></i>
                    </div>
                }
                <div class="notification-content">
                    @if (TempData["Message"]?.ToString()?.Split("/")[0] == "Success")
                    {
                        <p class="notification-header-success">Sukces!</p>
                    }
                    else
                    {
                        <p class="notification-header-error">Błąd!</p>
                    }
                    <p class="notification-message">@TempData["Message"]?.ToString()?.Split("/")[1]</p>
                </div>
                <div class="hide-notification">
                    <i class="fa-solid fa-xmark"></i>
                </div>
            </div>
        }
    }

</div>
<script src="~/js/Employees/ModalDialogRunner.js"></script>
<script src="~/js/Borrowing/Notification.js"></script>